[theme]
# Primary accent color for interactive elements.


# Background color for the main content area.


# Background color used for the sidebar and most interactive widgets.


# Color used for almost all text.


[client]
toolbarMode = "minimal"